### PR TITLE
docs: remove unused `NonNull` imports

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
Thanks!

**Comment by phil-opp** [comment]
Could you fix the doc warnings (which are now errors) for the `unstable` and `very_unstable` features as well? Alternatively, we could also keep the warning level at `warn` instead of `deny` by default and only deny warnings for the stable "Test Suite" job.

**Comment by mkroening** [comment]
> Could you fix the doc warnings (which are now errors) for the `unstable` and `very_unstable` features as well?

Ah, yes. Done. 👍

**Comment by phil-opp** [comment]
Thanks!

**Pull request merged**
