### PR TITLE
[v0.5] New design with two wrapper types: `VolatilePtr` and `VolatileRef`

### LINKED ISSUE #39: This crate is currently unsound due to spurious reads
As pointed out in https://github.com/japaric/vcell/issues/10, crates like this that use references to mmio are unsound.

I propose a new design that only stores raw pointers to prevent this behavior.
We could then initialize the cell using [`addr_of_mut`](https://doc.rust-lang.org/stable/std/ptr/macro.addr_of_mut.html) to avoid any creation of references before that data is initialized.
```rust
pub struct VolatileCell<T> {
    ptr: *mut T,
}

impl<T> VolatileCell<T> {
    pub fn new(ptr: *mut T) -> Self {
        Self { ptr }
    }

    pub fn get(&self) -> T
    where
        T: Copy,
    {
        unsafe { self.ptr.read_volatile() }
    }

    pub fn get_mut(&self) -> T
    where
        T: Copy,
    {
        unsafe { self.ptr.read_volatile() }
    }
}
```

### PR DESCRIPTION
**Pull request by phil-opp**
This draft PR is a follow-up to https://github.com/rust-osdev/volatile/pull/22. There was a lot of good discussion on that PR, mostly about the question whether the volatile wrapper type should implement `Copy` or `Send`. Implementing both of these traits would not be safe because it would allow unsynchronized concurrent writes from different threads.

I think that both approaches are valid, each with its advantages and drawbacks. For this reason, I tried to implement them both in this PR, as a base for further discussion. The following table summarizes the fundamental differences between the two pointer types:

|        | **`VolatilePtr`** | `VolatileRef`
|------|--------------------------------|------------------------
|Behavior | Behaves like Rust's raw pointer types. Implement `Copy`, but are not `Send`. | Behaves like Rust's reference types. Implement `Send` if `T: Sync` and implement `Copy` only if no mutation is allowed.
|Usable with `Mutex` types | :heavy_multiplication_x: <br>Mutex types require `Send`, but `VolatilePtrCopy` is `!Send` because writing the pointer from different threads would be UB.<br><i>Workaround: Create a custom wrapper type that unsafely implements `Send`</i> | :heavy_check_mark:  <br>Type can safely implement `Send` since writes require a `&mut` reference and type is not clonable.
| `read` and `write` methods are safe to call (after unsafe construction) | ( :heavy_check_mark: ?) <br>Implements `Copy`, so multiple instances can point to the same address. However, the instances are bound to a single thread, so concurrent writes should not be possible. We never construct `&mut` references, so we should not have mutable aliasing. | :heavy_check_mark: <br>Writes require an `&mut self` and the type is not clonable, so concurrent writes should not be possible even when used concurrently.
| Ease of use | :+1: <br>No borrow conflicts since all methods simply copy the pointer | :-1: <br>Methods borrow self, which requires [manual reborrows](https://github.com/rust-lang/rfcs/issues/1403) and makes splitting struct pointers into field pointers difficult.<br><i>Workaround: We could create an unsafe `duplicate` function that could be used for splitting a struct pointer into multiple field pointers. Maybe it's also possible to create a safe macro for this use case.

To simplify this PR and focus the discussion, I removed the unsafe access types for now. We can add them later once we settled on a fundamental API design. I also moved the `unstable` and `very_unstable` functions to separate submodules, so we can ignore them too for now.

Fixes https://github.com/rust-osdev/volatile/issues/39

### CODE REVIEW

**Comment by Lokathor** [comment]
There's plenty of single-**core** devices, but if they have an interrupt handler then that's modeled as an additional thread that executes sometimes. If your interrupt handler is doing anything interesting, then there ends up not being very many actually single-**threaded** situations.

But if you do have just one core, then both the main thread and interrupt thread could safely have a volatile pointer to the same place because they will never race with each other anyway. The only problems arise if you've got a multi-core device.

**Comment by phil-opp** [comment]
> But if you do have just one core, then both the main thread and interrupt thread could safely have a volatile pointer to the same place because they will never race with each other anyway.

I'm not sure if I understand this part. How is it not a data race if e.g. the main thread is interrupted in the middle of a write and the interrupt handler then writes (parts of) the same data?

**Comment by Lokathor** [comment]
https://llvm.org/docs/LangRef.html#memory-model-for-concurrent-operations

The general answer from llvm is that "What happens is target dependent.", though a good follow-up to that is probably "does the CPU honestly allow an interrupt to fire *during* an instruction anyway? because if it doesn't then you're worrying about a situation that can't happen."

In terms of MMIO, for all the compiler knows the value you volatile read might have nothing to do with anything you ever volatile wrote, so this isn't really a big deal.

**Comment by Freax13** [comment]
> https://llvm.org/docs/LangRef.html#memory-model-for-concurrent-operations
> 
> The general answer from llvm is that "What happens is target dependent.", though a good follow-up to that is probably "does the CPU honestly allow an interrupt to fire _during_ an instruction anyway? because if it doesn't then you're worrying about a situation that can't happen."

Volatile writes are not always one instruction though. If the type to be written is too big, the write may be split up into multiple instructions: https://godbolt.org/z/6vKjTsn6x.

**Comment by Lokathor** [comment]
That's true. Programmers are strongly advised to not declare their MMIO API in a way that accesses can tear.

**Comment by josephlr** [comment]
I think that the usability guarantees of `VolatilePtrCopy` outweigh the fact that you cannot share it between threads, so I think we should go with the `Copy` approach. Looking a the type parameters, I view `VolatilePtr` as allowing a user a certain type of access (determined by `A`) to a particular memory region (length and alignment determined by `T`) for a particular time (determined by `'a`). I think having the type not be `Send` reflects the fact that this grant is limited in scope.

If users want to share some volatile memory region between (including interrupt handlers), some sort of synchronization will be needed (as we cannot guarantee atomicity of a volatile operation). Such a `VolatileCell` could be added in a followup PR, which acts sort of like a `Mutex` giving out `!Send` `VolatilePtr` handles, similar to how `MutexGuard` (which is also `!Send`) works in libstd today.

**Comment by Lokathor** [comment]
The usual Mutex/Handle based API doesn't work quite so well with interrupt handlers because when you're the main thread you know that the interrupt handler isn't *ever* holding the lock (because it starts and stops between your own instructions), and if you're the interrupt handler and the lock is currently held by main you can't ever wait for the lock to be released because you're the thing preventing main from executing. So, while the interrupt handler is in some ways modeled as a separate thread, it's in other ways its own weird thing that requires its own consideration. Also, some platforms are so old they don't support the usual atomics, so even communicating if the lock is held or not can be a pain in the butt and/or wildly inefficient.

**Comment by mkroening** [comment]
I would expect a `VolatilePtrSend` with read and write access to closely resemble a `&mut T`, except every access is explicit and volatile. This could be called `VolatilePtr` or `VolatileMut` as per the `std` convention (might be unwieldy though). That way, I could allocate a MMIO address once with static lifetime and then share it between cores in a self-provided mutex (or a thread-safe mutex if also accessed in an interrupt handler).

A `VolatilePtrCopy` I would expect to closely resemble [`&core::cell:Cell<T>`](https://doc.rust-lang.org/stable/core/cell/struct.Cell.html). `VolatileCellRef` might be a bit of a mouth full, so I'd call this `VolatileCell`. In my mind, this is not of much use when different cores access the same memory. The synchronization required when creating/dropping this type sounds like it might better be handled by putting a longer lived ptr of `Send` version into a mutex. Still, there seems to be interest in this type as well, so it might be best to provide both types.

Another type that I just thought of is a `VolatileAtomicPtr`, where the inner type is an `AtomicPtr` to allow for synchronization without blocking. This is not thought to the end though, so feel free to disregard this thought.

**Comment by phil-opp** [comment]
Thanks a lot for your thoughts!

> I think that the usability guarantees of `VolatilePtrCopy` outweigh the fact that you cannot share it between threads, so I think we should go with the `Copy` approach.

Sharing a volatile across threads and interrupt handlers seems like a common use case, so I think we should really provide a `Send` type. Otherwise most uses of this crate would need to create their own unsafe wrapper types.

> If users want to share some volatile memory region between (including interrupt handlers), some sort of synchronization will be needed (as we cannot guarantee atomicity of a volatile operation). Such a `VolatileCell` could be added in a followup PR, which acts sort of like a `Mutex` giving out `!Send` `VolatilePtr` handles, similar to how `MutexGuard` (which is also `!Send`) works in libstd today.

Interesting idea! I like the `Mutex`/`MutexGuard` analogy. So maybe it really makes sense to provide both variants in some form...

> The usual Mutex/Handle based API doesn't work quite so well with interrupt handlers

Agreed! Also, there is not really a good general way to implement mutexes in `no_std` programs since spinlocks have a lot of drawbacks (see e.g. the discussion in https://github.com/rust-lang/rust/issues/74465y). So it's better to let the users provide the mutex type in my opinion. This way, they can also define their own invariants and e.g. panic or force-unlock if a lock is held unexpectedly. As @mkroening noted, this already possible with the `VolatilePtrSend` type.

---

How about the following design:

- We keep `VolatilePtrCopy` as-is, we just try to find a better name later.
- We also keep `VolatilePtrSend`, but remove most of its methods.
- Instead, we provide two new conversion methods:
  - `fn as_ref<'b>(&'b self) -> VolatilePtrCopy<'b, T, A::RestrictShared>;`
  - `fn as_mut<'b>(&'b mut self) -> VolatilePtrCopy<'b, T, A>;`

So the `VolatilePtrSend` type becomes a wrapper type that prevents shared mutable aliasing and can thus safely provide a `Send` implementation.

_Edit:_ I prototyped such `as_ref`/`as_mut` methods in 42fe49deb12b1fd21fbb8244335fbf39305dbc6e.

**Comment by phil-opp** [comment]
> Another type that I just thought of is a `VolatileAtomicPtr`, where the inner type is an `AtomicPtr` to allow for synchronization without blocking. This is not thought to the end though, so feel free to disregard this thought.

I like that idea! `AtomicPtr` is probably not the right type though since we want to change the value behind the pointer, not the pointer itself. Also, we might need references instead of pointers to use the atomic instructions of the stdlib, which leads to aliasing questions again. So I think it's best to discuss this in a separate issue. I opened https://github.com/rust-osdev/volatile/issues/30 for that.

**Comment by Lokathor** [comment]
The design here seems to be straining because it's trying to handle a lot of situations I didn't really have to handle myself, so you have my condolences.

One thing I'll point out is that read/write access isn't the only axis, you probably want a way to model safe/unsafe access too.

**Comment by phil-opp** [comment]
Update:

> How about the following design:
> 
>     * We keep `VolatilePtrCopy` as-is, we just try to find a better name later.
> 
>     * We also keep `VolatilePtrSend`, but remove most of its methods.
> 
>     * Instead, we provide two new conversion methods:
>       
>       * `fn as_ref<'b>(&'b self) -> VolatilePtrCopy<'b, T, A::RestrictShared>;`
>       * `fn as_mut<'b>(&'b mut self) -> VolatilePtrCopy<'b, T, A>;`
> 
> 
> So the `VolatilePtrSend` type becomes a wrapper type that prevents shared mutable aliasing and can thus safely provide a `Send` implementation.

I think this is the most promising solution. We need nicer names though, so I renamed the `Copy` type to `VolatilePtr` and the non-`Copy` type to `VolatileRef`. I also removed all access methods from `VolatileRef` and documented that the new `as_ptr()`/`as_mut_ptr()` methods should be used instead, which create temporary `VolatilePtr` instances. This way, we avoid most of the code duplication while keeping the crate flexible.

I also drafted up a short introduction of the two types for our crate docs:

> This crate provides two different wrapper types: [`VolatilePtr`] and [`VolatileRef`]. The
difference between the two types is that the former behaves like a raw pointer, while the
latter behaves like a Rust reference type. For example, `VolatilePtr` can be freely copied,
but not sent across threads because this could introduce mutable aliasing. The `VolatileRef`
type, on the other hand, requires exclusive access for mutation, so that sharing it across
thread boundaries is safe.

Given that the API of the current release is not sound, I'm favor of merging this PR soon. We can continue improving the API and implementation in future PRs. The only thing that I want to do before merging is to write proper docs for all methods.

**Comment by Lokathor** [comment]
I'm trying to page things back into my memory, but this sounds like *basically* a "more restrictive than theoretically necessary, but at least we know it is sound" solution. Is that right? If so, I would agree to merge it now and if possible improve it later (again, if possible).

**Comment by mkroening** [comment]
There is a relevant discussion on having a `VolatileCell` as a language feature: https://github.com/rust-lang/unsafe-code-guidelines/issues/411

**Comment by phil-opp** [comment]
Published as v0.5.0

**Pull request merged**
